name: Atualizar Painel REST do Quarto

on:
  schedule:
    - cron: '0 * * * *'    # roda a cada hora
  workflow_dispatch:      # permite rodar “manualmente” na UI

jobs:
  build:
    runs-on: ubuntu-latest

    # 1) Aqui você injeta os seus secrets em ENV vars
    env:
      HA_URL:            ${{ secrets.HA_URL }}
      HA_TOKEN:          ${{ secrets.HA_TOKEN }}
      CALENDAR_ID:       ${{ secrets.CALENDAR_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install requests speedtest-cli holidays \
                      google-api-python-client google-auth

      - name: Gerar painel HTML
        run: python get_painel_quarto.py

      - name: Publicar no GitHub Pages
        run: |
          mkdir -p docs
          mv docs/index.html docs/index.html
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/index.html
          git commit -m "Atualização automática do painel" || echo "Sem mudanças"
          git push
